[package]
name = "xsd-core"
version = "0.15.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
quick-xml = "0.42"
regex = "1"
xml-core = { path = "../xml-core" }

[dev-dependencies]
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "xsd_core"
harness = false
