[workspace]
members = [
    ".",
    "crates/xml-core",
    "crates/xsd-core",
    "crates/dtd-core",
    "crates/xml-lsp",
    "crates/xml-conformance",
]
resolver = "2"

[package]
name = "zed-xml"
version = "0.10.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
