[package]
name = "xml-core"
version = "0.13.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
quick-xml = "0.38"

[dev-dependencies]
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }

[[bench]]
name = "xml_core"
harness = false
